<?php 
 if($block->isEnquiryEnabled()){
   if($block->getFormType()==false){
     if($block->getProduct()->getInquiry()){
?>
<div style="padding-bottom: 30px;">
  <button style="background-color:#006bb4;color:white;" type="button" class="btn btn-primary btn-lg" id="popupButton"
    data-toggle="modal" data-target="#myModal">
    <?php echo __($block->getButtonLavel())?>
  </button>
</div>
<!-- Modal -->

<!-- Modal content -->
<div class="modal fade" id="myModal" style="display:block;">
  <div class="modal-dialog">
    <!-- Modal content -->
    <div class="modal-content">

      <div class="modal-body">
        <form data-mage-init='{"validation": {}}' class="review-form" action="<?php echo $block->getPathUrl() ?>"
          id="my-form" method="post" autocomplete="on">
          <fieldset class="fieldset">
            <div class="field name required">
              <label class="label" for="field-1"><span>
                  <?php echo __('Name');?>
                </span></label>
              <input type="text" class="form-control" data-validate='{"required":true}' maxlength="20" id="field-1"
                value='<?php if($block->getCustomer()->getName() != " "){ echo $block->getCustomer()->getName();}?>' placeholder="<?php echo __('Enter name')?>" name="c_name">

            </div>
            <div class="field name required">
              <label class="label" for="field-2"><span>
                  <?php echo __('Email');?>
                </span></label>
              <input type="email" data-validate="{required:true, 'validate-email':true}" class="form-control"
                id="field-2" value="<?php echo $block->getCustomer()->getEmail();?>"
                placeholder="<?php echo __('Enter email')?>" name="email">
            </div>
            <div class="field name required">
              <label class="label" for="field-3"><span>
                  <?php echo __('Telephone');?>
                </span></label>

              <input type="number" data-validate='{"required":true}' class="form-control" id="field-3"
                placeholder="<?php echo __('Enter Telephone')?>" pattern="\d{10}" maxlength="10" minlength="10"
                name="telephone">
            </div>

            <input type="hidden" data-validate='{"required":true}'
              value="<?php echo $block->getProduct()->getSku(); ?>" readonly class="form-control" id="field-52"
              name="sku">

              <input type="hidden" data-validate='{"required":true}' value="<?php echo $block->getProduct()->getId(); ?>"
      readonly class="form-control" id="field-53" name="product_id">


            <input type="hidden" data-validate='{"required":true}'
              value="<?php echo $block->getProduct()->getName();?>" readonly class="form-control" id="field-54"
              name="product_name">

            <input type="hidden" data-validate='{"required":true}'
              value="<?php echo $block->getProduct()->getProductUrl();?>" class="form-control" id="field-55"
              placeholder="<?php echo __('Enter Subject')?>" name="producturl">

            <div class="field name required">
              <label class="label" for="field-4"><span>
                  <?php echo __('Subject');?>
                </span></label>

              <input type="text" data-validate='{"required":true}' maxlength="50" class="form-control" id="field-4"
                placeholder="<?php echo __('Enter Subject')?>" name="subject">
            </div>
            <div class="field name required">
              <label class="label" for="field-5"><span>
                  <?php echo __('Message');?>
                </span></label>

              <textarea class="form-control" data-validate='{"required":true}' maxlength="500" rows="5" id="field-5"
                name="massage"></textarea>
            </div>
            
          </fieldset>
             
          <button style="background-color:#006bb4;color:white;" type="submit" class="btn btn-default">
            <?php echo __('Submit')?>
          </button>
        </form>
      </div>
    </div>
  </div>
</div>



<script>
  require(
      [
          'jquery',
          'Magento_Ui/js/modal/modal'
      ],
      function (
          $,
          modal
      ) {
          var options = {
              type: 'popup',
              responsive: true,
              innerScroll: true,
              clickableOverlay: true,
              title: 'Product Enquiry',
              buttons: [{
                  text: $.mage.__(''),
                  class: '',
                  click: function () {
                      this.closeModal();
                  }
              }]
          };

          var popup = modal(options, $('#myModal'));
          $("#popupButton").on('click', function () {
              $("#myModal").modal("openModal");
          });

      }
  );
</script>
<script type="text/x-magento-init">
    {
        "#my-form": {
            "validation": {}
        }
    }
</script>

<?php
      }
    }
}



?>